//Source code generated by AppGPT (www.appgpt.tech)
import { mergeTranslations } from 'ra-core';
import polyglotI18nProvider from 'ra-i18n-polyglot';
import enOriginal from 'ra-language-english';
import frOriginal from 'ra-language-french';

const enResources = {
  resources: {
    Tracks: {
      name: 'Tracks',
      fields: {
        artist: 'Artist',
        title: 'Title',
        genre: 'Genre',
        releaseDate: 'Release Date',
        id: 'id',
      },
    },
    Artists: {
      name: 'Artists',
      fields: { name: 'Name', genre: 'Genre', tracks: 'Tracks', id: 'id' },
    },
    Albums: {
      name: 'Albums',
      fields: {
        title: 'Title',
        releaseDate: 'Release Date',
        artist: 'Artist',
        tracks: 'Tracks',
        genre: 'Genre',
        id: 'id',
      },
    },
    Playlists: {
      name: 'Playlists',
      fields: { name: 'Name', creator: 'Creator', tracks: 'Tracks', id: 'id' },
    },
    Users: {
      name: 'Users',
      fields: {
        username: 'Username',
        email: 'Email',
        password: 'Password',
        playlists: 'Playlists',
        id: 'id',
      },
    },
  },
};
const frResources = {
  resources: {
    Tracks: {
      name: 'Tracks (fr)',
      fields: {
        artist: 'Artist (fr)',
        title: 'Title (fr)',
        genre: 'Genre (fr)',
        releaseDate: 'Release Date (fr)',
        id: 'id',
      },
    },
    Artists: {
      name: 'Artists (fr)',
      fields: {
        name: 'Name (fr)',
        genre: 'Genre (fr)',
        tracks: 'Tracks (fr)',
        id: 'id',
      },
    },
    Albums: {
      name: 'Albums (fr)',
      fields: {
        title: 'Title (fr)',
        releaseDate: 'Release Date (fr)',
        artist: 'Artist (fr)',
        tracks: 'Tracks (fr)',
        genre: 'Genre (fr)',
        id: 'id',
      },
    },
    Playlists: {
      name: 'Playlists (fr)',
      fields: {
        name: 'Name (fr)',
        creator: 'Creator (fr)',
        tracks: 'Tracks (fr)',
        id: 'id',
      },
    },
    Users: {
      name: 'Users (fr)',
      fields: {
        username: 'Username (fr)',
        email: 'Email (fr)',
        password: 'Password (fr)',
        playlists: 'Playlists (fr)',
        id: 'id',
      },
    },
  },
};

const en = mergeTranslations(enOriginal, enResources);
const fr = mergeTranslations(frOriginal, frResources);

const translations = { en, fr };
export const i18nProvider = polyglotI18nProvider(
  (locale) => translations[locale],
  'en', //default locale
  [
    { locale: 'en', name: 'English' },
    { locale: 'fr', name: 'Français' },
  ],
);
